### PR TITLE
fix: koa render decorator

### PR DESCRIPTION
**Pull request by Jiasm**
When `@Render` exec, that will add a new `middleware`.
Just call `render` to return results.

### CODE REVIEW

**Comment by Jiasm** [comment]
That a big bugs [#378].

Please merge it.

A little change to use:

```javascript
const koa = new Koa()
koa.use(koaViews(path.join(__dirname, '../views'), {
  options: {
    ext: 'ejs',
  },
  extension: 'ejs',
}))

const app = useKoaServer(koa, {
  controllers: [`${__dirname}/controllers/**/*{.js,.ts}`],
})

app.use(serve(distPath))
app.use(bodyParser())
```

**Comment by 19majkel94** [comment]
@Jiasm Changes looks good but the tests for render on koa and older node.js versions fails (HTTP error 500). Could you check out this and fix it?

**Comment by Jiasm** [comment]
@19majkel94 I will fixed it at tomorrow.
Now is 22:40 :) (I'm in China)

**Comment by Jiasm** [comment]
@19majkel94 The Travis CI hang on too long time :(

**Comment by 19majkel94** [comment]
@Jiasm I see but I don't know what's going on 😕

**Comment by Jiasm** [comment]
Finally... it worked.
I'm going to bed, good night.

**Comment by ninja-** [comment]
:/

**Comment by morrislaptop** [comment]
This should be closed in favour of #409

**Pull request closed without merging**
