### PR TITLE
build(deps): bump class-transformer and class-validator version

### LINKED ISSUE #783: Please update class-transformer dependency to the latest version
Hello!

Thank you for this great library!

However, right now it requires `class-transformer@0.3.1` (exact version `0.3.1`) as a peer dependency. This prevents my project from using the latest version of the `class-transformer` (which is `0.4.0`).

This generates the following error on `npm install`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @acme/project
npm ERR! Found: class-transformer@0.4.0
npm ERR! node_modules/class-transformer
npm ERR!   class-transformer@"0.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer class-transformer@"^0.3.1" from routing-controllers@0.9.0
npm ERR! node_modules/routing-controllers
npm ERR!   routing-controllers@"0.9.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Would you be so kind to update `class-transformer` dependency to the latest version?

Thanks!

### PR DESCRIPTION
**Pull request by gtpan77**
## Description
Version bump of peer dependencies `class-transformer` and `class-validator`.
Resolves https://github.com/typestack/routing-controllers/issues/783

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [ ] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes
fixes #783

### CODE REVIEW

**Comment by DAlperin** [comment]
@NoNameProvided do you mind giving this a review/merge when you get a chance? This is unfortunately breaking ci for a number of users.

**Comment by biton-ron** [comment]
@NoNameProvided Hey! This version of class-validator includes a very important validation setting `stopAtFirstError` that is not possible to activate at the moment. Thank! :)

**Comment by FrancisBehnen** [comment]
Would it be an idea to publish a version with bumped dependencies to another NPM registry? I'm trying to use this branch, but running into issues because the typescript is not transpiled to javascript if I use the repo directly. https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by attilaorosz** [comment]
Closing this as it is addressed already in a different PR

**Pull request closed without merging**
