### PR TITLE
Feat/update project tooling

### PR DESCRIPTION
**Pull request by NoNameProvided**
## Description

Add the shared project tooling from the other repository

## Checklist

- [ ] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [ ] the pull request targets the *default* branch of the repository (`develop`)
- [ ] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [ ] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [ ] I have run the project locally and verified that there are no errors

### Fixes

fixes #[issue number], fixes #[issue number]

### CODE REVIEW

**Comment by NoNameProvided** [comment]
CC @jotamorais, @rmuchall some tests are still failing. @rmuchall I use the same test in most of the places which you wrote, how did you manage to make them pass?

**Comment by rmuchall** [comment]
I took a quick look at the branch /feat/update-project-tooling and I can see 11 failed tests.
Do you get the same results?

Scanning through the errors they look like bugs in the tests themselves (or perhaps just changes in the routing-controllers functionality where the test code hasn't been updated to match). I don't see any tests specifically failing due to the use of Jest/Axios.

**Comment by NoNameProvided** [comment]
> Scanning through the errors they look like bugs in the tests themselves

Yes but as I mentioned, the tests are shamelessly copied from your PR, so I would expect them to pass. 

>  (or perhaps just changes in the routing-controllers functionality where the test code hasn't been updated to match)

I don't think that much functionality has changed. 

Anyway, thanks for the look! I will look into those when I have time (they look nasty, concurrency issues) I just hoped I have missed some flag or something :D

**Comment by rmuchall** [comment]
Are you seeing the same amount of failed test? (11)
If they look like concurrency issues then it might be related to the "runInBand" issue we encountered.
See here for details: https://github.com/typestack/routing-controllers/pull/553#issuecomment-618512557

**Comment by NoNameProvided** [comment]
Why did we merge this with failing tests?

**Pull request merged**
